name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/

  train_and_quantize:
    runs-on: ubuntu-latest
    needs: test_suite
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
        python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train and Quantize
        run: |
          python src/train.py
          python src/quantize.py

  docker_build:
    runs-on: ubuntu-latest
    needs: train_and_quantize
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t mlops-linear-regression .

      - name: Run Docker Container
        run: docker run --rm mlops-linear-regression
